#!/bin/env python

from astropy.io import fits

import pandas as pd
import numpy as np
import binary_gamma_errs as bge
import sys
import tqdm

print("Reading input...")

fits_data = fits.open(sys.argv[1])
data = pd.DataFrame.from_records(fits_data[1].data)

print("Calculating gammas...")

gamma_mean = []

for system in tqdm.tqdm(data.iloc, total=len(data)):
    system_gamma = bge.get_gamma(system)
    gamma_mean.append(system_gamma)

data["gamma"] = gamma_mean

print("Writing file")

data.to_csv(sys.argv[2])
